myshop/cart/urls.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

myshop/myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
]

myshop/shop/models.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

from django.db import models

# Модель категории
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])

# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/', blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id, self.slug])

myshop/cart/views.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myshop.shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# #Отображение формы для выбора количества товара, а второе поле проверяет если товар ранее был добавлен в корзину



@require_POST
def CartAdd(request, product_id):
     cart = Cart(request)
     product = get_object_or_404(Product, id=product_id)
     form = CartAddProductForm(request.POST)
     if form.is_valid():
         cd = form.cleaned_data
         cart.add(product=product, quantity=cd['quantity'],
                                   update_quantity=cd['update'])
     return redirect('cart:CartDetail')

# #Возможность удалять товары
def CartRemove(request, product_id):
     cart = Cart(request)
     product = get_object_or_404(Product, id=product_id)
     cart.remove(product)
     return redirect('cart:CartDetail')

# #Отображение корзины
def CartDetail(request):
     cart = Cart(request)
     return render(request, 'cart/detail.html', {'cart': cart})

myshop/shop/views.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product


# Страница с товарами
def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'shop/product/detail.html', {'product': product})

myshop/shop/templates/cart/detail.html
{% extends "shop/base.html" %}

{% block title %}
    Ваша корзина товаров
{% endblock %}

{% block content %}
    <h1>Ваша корзина товаров</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Изображение</th>
                <th>Продукт</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Полная цена</th>
                <th>Цена</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" alt="" />
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td><a href="{% url 'cart:CartRemove' product.id %}">Удалить</a></td>
                <td class="num">{{ item.price }} руб.</td>
                <td class="num">{{ item.total_price }} руб.</td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price }} руб.</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:ProductList'%}" class="btn">Продолжить Шопинг</a>
        <a href="#">Оформить заказ</a>
    </p>
{% endblock %}

myshop/shop/templates/shop/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <!-- Styles>-->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <section id="header">
            <div class="top container">Мой Онлайн-Магазин</div>
            <div class="top-bl">
                <div class="container">
                    <div class="cart">Ваша корзина пуста</div>
                </div>
            </div>
        </section>
        <section id="content row" class="container">
            {% block content %}{% endblock %}
        </section>
    </body>
</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}

{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <div class="col-sm-4">
             <img src="{% if product.image %}{{ product.image.url }}{% else %}
             {% static 'img/no-image.jpg' %}{% endif %}" class="img-responsive" alt="My image" />
        </div>
        <div class="col-sm-8">
            <h1>{{ product.name }}</h1>
            <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
            <p class="price">{{ product.price }} руб.</p>
            <form action="{% url 'cart:CartAdd' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину">
            </form>
            <span>
                {{ product.description | linebreaks}}
            </span>
        </div>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar" class="col-sm-3">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %} class="selected" {% endif %}>
                <a href="{% url 'shop:ProductList' %}">Все</a>
            </li>
            {% for cat in categories %}
                <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
                    <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product_list col-sm-9">
        <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
        <div class="items row">
            {% for product in products %}
            <div class="item col-sm-4">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}
                    {% static 'img/no-image.jpg' %}{% endif %}" class="img-responsive" alt="My image" />
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br />
                {{ product.price }} руб.
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}